#!/bin/bash
option="-link"
url="https://igicheva.wordpress.com/all-posts/"

python main.py $option $url
READ=$?
if [ "$READ" -eq "0" ]
then
	export FLASK_APP=module/web_interface/json_to_html
	flask run
else
	echo "Web Scraper error"
fi
